function export_clipboard(parent)

% Controls for MS Word export
    uicontrol('Style', 'text',...
        'parent', parent,...
        'string', 'Title:',...
        'position', [50 450 100 20]);
    
    data.title = uicontrol('Style', 'edit',...
        'parent', parent,...
        'BackgroundColor', 'white',...
        'position', [150 450 100 20]);
    
    uicontrol('Style', 'text',...
        'parent', parent,...
        'string', 'X-label:',...
        'position', [50 425 100 20]);
    
    data.xlabel = uicontrol('Style', 'edit',...
        'parent', parent,...
        'BackgroundColor', 'white',...
        'position', [150 425 100 20]);
    
    uicontrol('Style', 'text',...
        'parent', parent,...
        'string', 'Y-label:',...
        'position', [50 400 100 20]);
    
    data.ylabel = uicontrol('Style', 'edit',...
        'parent', parent,...
        'BackgroundColor', 'white',...
        'position', [150 400 100 20]);
    
    uicontrol('Style', 'pushbutton',...
        'parent', parent,...
        'String', 'Export',...
        'position', [100 250 100 25],...
        'callback', {@copy,data});
    
function copy(~,~,data)
    try
        %Copy figure to clipboard
   	    tmp_figure = open('figure.fig');
        set(tmp_figure,'Visible', 'Off');
        title(get(data.title, 'String'));
        xlabel(get(data.xlabel, 'String'));
        ylabel(get(data.ylabel, 'String'));
		    print(tmp_figure, '-dmeta');
		    close(tmp_figure);
    
    catch error
        msgbox(error.getReport, 'Image not copied!', 'warn');
    end