function export_latex(parent)
% Controls for Latex figure export
    uicontrol('Style', 'text',...
        'parent', parent,...
        'string', 'Image name:',...
        'position', [50 500 100 20]);
    
    data.figure_name = uicontrol('Style', 'edit',...
        'parent', parent,...
        'string', 'fig',...
        'BackgroundColor', 'white',...
        'position', [150 500 100 20]);
    
    
    uicontrol('Style', 'text',...
        'parent', parent,...
        'string', 'Caption:',...
        'position', [50 450 100 20]);
    
    data.figure_caption = uicontrol('Style', 'edit',...
        'parent', parent,...
        'BackgroundColor', 'white',...
        'position', [150 450 100 20]);
    
    uicontrol('Style', 'text',...
        'parent', parent,...
        'string', 'Label:',...
        'position', [50 400 100 20]);
    
    data.figure_label = uicontrol('Style', 'edit',...
        'parent', parent,...
        'BackgroundColor', 'white',...
        'position', [150 400 100 20]);
    
    uicontrol('Style', 'text',...
        'parent', parent,...
        'string', 'Width [cm]:',...
        'position', [50 350 100 20]);
    
    data.figure_width = uicontrol('Style', 'edit',...
        'parent', parent,...
        'string', '5',...
        'BackgroundColor', 'white',...
        'position', [150 350 100 20]);


    uicontrol('Style', 'pushbutton',...
        'parent', parent,...
        'String', 'Export',...
        'position', [100 250 100 25],...
        'callback', {@save,data});
end
function save(~,~,data)
    [fileName,pathName] = uiputfile();
    outFile = fopen([pathName, fileName], 'wt');
    
    fprintf(outFile,...
        ['\\documentclass{article}\n\\begin{document}\n',...
        '\\begin{figure}\n\\centering\n',...
        '\\includegraphics[width=',...
        get(data.figure_width, 'string'),...
        'cm]{',...
        get(data.figure_name, 'string'),...
        '}\n',...
        '\\caption{',...
        get(data.figure_caption, 'string'),...
        '}\n',...
        '\\label{',...
        get(data.figure_label, 'string'),...
        '}\n',...
        '\\end{figure}\n',...
        '\\end{document}']);
    fclose(outFile);
end