function export_clipboard(parent)

% Controls for MS Word export
    uicontrol('Style', 'text',...
        'parent', parent,...
        'string', 'Title:',...
        'HorizontalAlignmen', 'right',...
        'BackgroundColor', 'white',...
        'position', [30 600 60 20]);
    
    data.title = uicontrol('Style', 'edit',...
        'parent', parent,...
        'BackgroundColor', 'white',...
        'position', [100 600 100 20]);
    
    uicontrol('Style', 'text',...
        'parent', parent,...
        'string', 'X-label:',...
        'HorizontalAlignmen', 'right',...
        'BackgroundColor', 'white',...
        'position', [30 550 60 20]);
    
    data.xlabel = uicontrol('Style', 'edit',...
        'parent', parent,...
        'BackgroundColor', 'white',...
        'position', [100 550 100 20]);
    
    uicontrol('Style', 'text',...
        'parent', parent,...
        'string', 'Y-label:',...
        'HorizontalAlignmen', 'right',...
        'BackgroundColor', 'white',...
        'position', [30 500 60 20]);
    
    data.ylabel = uicontrol('Style', 'edit',...
        'parent', parent,...
        'BackgroundColor', 'white',...
        'position', [100 500 100 20]);
    
    uicontrol('Style', 'pushbutton',...
        'parent', parent,...
        'String', 'Copy',...
        'position', [70 450 100 20],...
        'callback', {@copy,data});
    
function copy(~,~,data)
    try
        %Copy figure to clipboard
   	    tmp_figure = open('figure.fig');
        set(tmp_figure,'Visible', 'Off');
        title(get(data.title, 'String'));
        xlabel(get(data.xlabel, 'String'));
        ylabel(get(data.ylabel, 'String'));
		    print(tmp_figure, '-dmeta');
		    close(tmp_figure);
    
    catch error
        msgbox(error.getReport, 'Image not copied!', 'warn');
    end