
    % Controls for function generator
    uicontrol('Style', 'text',...
        'string', 'Frequency [Hz]:',...
        'position', [50 600 100 20]);
    
    uicontrol('Style', 'edit',...
        'string', '1000',...
        'BackgroundColor', 'white',...
        'position', [150 600 50 25]);

    uicontrol('Style', 'text',...
        'string', 'Amplitude [V]:',...
        'position', [50 550 100 20]);
    
    uicontrol('Style', 'edit',...
        'string', '5',...
        'BackgroundColor', 'white',...
        'position', [150 550 50 25]);

    uicontrol('Style', 'text',...
        'string', 'Offset [V]:',...
        'position', [50 500 100 20]);
    
    uicontrol('Style', 'edit',...
        'string', '2.5',...
        'BackgroundColor', 'white',...
        'position', [150 500 50 25]);
    