function none_chosen(parent)

        set(parent, 'Units', 'pixels');
        panel_size = get(parent, 'Position');
        center = panel_size(3)/2-75;
        
        uicontrol('Style', 'text',...
        'parent', parent,...
        'string', 't',...
        'BackgroundColor', 'white',...
        'ForegroundColor', [0.5 0.8 0.5],...
        'FontName', 'Marlett',...
        'FontSize', 60,...
        'position', [center 550 150 50]);
    
        uicontrol('Style', 'text',...
        'parent', parent,...
        'string', 'choose',...
        'BackgroundColor', 'white',...
        'ForegroundColor', [0.5 0.8 0.5],...
        'FontSize', 30,...
        'position', [center 450 150 50]);

end