function out_bodegraph(panel)
    % Controls for multimeter
    global multimeter;

    uicontrol('Style', 'text',...
            'parent', panel,...
            'string', 'Multimeter GPIB address:',...
            'HorizontalAlignmen', 'right',...
            'BackgroundColor', 'white',...
            'position', [30 600 120 20]);

    multimeter.gpibAddress =  uicontrol('Style', 'edit',...
            'parent', panel,...
            'string', '0',...
            'BackgroundColor', 'white',...
            'position', [160 600 60 20]);

end